"""Generate src/components/world/name-glyphs.ts, the outlines the name plate extrudes.

The plate is cut from a static wide instance of Anybody (wdth 150, wght 800), the
same cut the hero's display echo sets in CSS, so the 3D letters and the DOM text
share their shapes and their shaped advances (kerning included).

Usage (Python 3 with fonttools, uharfbuzz and skia-pathops installed):

    curl -LO "https://github.com/google/fonts/raw/main/ofl/anybody/Anybody%5Bwdth,wght%5D.ttf"
    python scripts/name-plate-glyphs.py "Anybody[wdth,wght].ttf"

Anybody is (c) 2020 The Anybody Project Authors, under the SIL Open Font License 1.1.
"""

import io
import json
import sys
from pathlib import Path

import uharfbuzz as hb
from fontTools.pens.basePen import BasePen
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import OverlapMode, instantiateVariableFont

WORDS = ["ADRIAN", "LUK"]
AXES = {"wdth": 150, "wght": 800}
OUT = Path(__file__).resolve().parent.parent / "src/components/world/name-glyphs.ts"


class OutlinePen(BasePen):
    """Records an outline as three.js-style commands: m x y, l x y, q cx cy x y, z."""

    def __init__(self, glyph_set, dx):
        super().__init__(glyph_set)
        self.dx = dx
        self.ops = []

    def _pt(self, pt):
        return [round(pt[0] + self.dx), round(pt[1])]

    def _moveTo(self, pt):
        self.ops += ["m", *self._pt(pt)]

    def _lineTo(self, pt):
        self.ops += ["l", *self._pt(pt)]

    def _qCurveToOne(self, pt1, pt2):
        self.ops += ["q", *self._pt(pt1), *self._pt(pt2)]

    def _curveToOne(self, pt1, pt2, pt3):
        raise ValueError("Anybody is TrueType: no cubic segments expected")

    def _closePath(self):
        self.ops += ["z"]


def main(src):
    font = TTFont(src)
    instance = instantiateVariableFont(font, AXES, overlap=OverlapMode.REMOVE)
    buf = io.BytesIO()
    instance.save(buf)
    data = buf.getvalue()
    font = TTFont(io.BytesIO(data))

    hb_font = hb.Font(hb.Face(data))
    glyph_set = font.getGlyphSet()
    upm = font["head"].unitsPerEm
    os2 = font["OS/2"]
    # Chrome sizes an inline box from the typo metrics when USE_TYPO_METRICS is set.
    assert os2.fsSelection & (1 << 7), "expected USE_TYPO_METRICS"

    words = {}
    for word in WORDS:
        buf = hb.Buffer()
        buf.add_str(word)
        buf.guess_segment_properties()
        hb.shape(hb_font, buf, {"kern": True})
        pen_x = 0
        ops = []
        for info, pos in zip(buf.glyph_infos, buf.glyph_positions):
            name = font.getGlyphName(info.codepoint)
            pen = OutlinePen(glyph_set, pen_x + pos.x_offset)
            glyph_set[name].draw(pen)
            ops += pen.ops
            pen_x += pos.x_advance
        words[word] = {"advance": pen_x, "outline": " ".join(map(str, ops))}

    out = {
        "unitsPerEm": upm,
        "ascender": os2.sTypoAscender,
        "descender": os2.sTypoDescender,
        "capHeight": os2.sCapHeight,
        "words": words,
    }
    OUT.write_text(
        "// Generated by scripts/name-plate-glyphs.py from Anybody (wdth 150, wght 800). Do not edit.\n"
        "// Anybody is (c) 2020 The Anybody Project Authors, under the SIL Open Font License 1.1.\n\n"
        f"export const nameGlyphs = {json.dumps(out, indent=2)} as const;\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main(sys.argv[1])
